add_newline=false

format = '''\[$username$hostname:$directory\]
$git_branch$git_state$git_status$character
'''

[package]
disabled = false

[username]
style_user = 'green'
style_root = 'red bold'
disabled = false
show_always = true

[hostname]
ssh_only = false
disabled = false
format = '[$ssh_symbol$hostname]($style)'

[directory]
truncation_length = 8
truncation_symbol = '$/'

[git_branch]
truncation_symbol = ''
ignore_branches = ['master', 'main']

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[git_state]
cherry_pick = '\[PICKING\](bold red)'
rebase = '\[REBASING\](bold purple)'
merge = '\[MERGING\](bold white)'

[git_status]
conflicted = '\[🏳CONFLICTED!!!\]'
ahead = '\[🏎💨 ahead\]'
behind = '\[😰 behind\]'
diverged = '\[😵 diverged\]'
up_to_date = '\[✓ up_to_date\]'
untracked = '\[🤷 untracked\]'
staged = '\[staged: ++\($count\)\](green)'
deleted = '\[🗑deleted \]'

[character]
